tap "buildkite/cli"
tap "buildpacks/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "linuxkit/linuxkit"
tap "mutagen-io/mutagen"
tap "outstand/desk"
tap "tylerbrock/saw"
tap "vitorgalvao/tiny-scripts"
tap "wagoodman/dive"
brew "ansible"
brew "ansible-lint"
brew "asciinema"
brew "awscli"
brew "b2-tools"
brew "bash"
brew "bat"
brew "bat-extras"
brew "caddy", restart_service: true
brew "ctags"
brew "curl"
brew "dialog"
brew "dnsmasq", restart_service: true
brew "docker-credential-helper", link: false
brew "dos2unix"
brew "duck"
brew "envconsul"
brew "exa"
brew "exercism"
brew "libbluray"
brew "fontforge"
brew "gh"
brew "ghi"
brew "gifski"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnupg"
brew "gptfdisk"
brew "graphviz"
brew "grv"
brew "httpie"
brew "hub"
brew "jq"
brew "kubernetes-cli"
brew "libaacs"
brew "libbdplus"
brew "libdvdcss"
brew "luajit", args: ["HEAD"]
brew "mas"
brew "minikube"
brew "mitmproxy"
brew "mkcert"
brew "mosh", args: ["HEAD"]
brew "neovim"
brew "nmap"
brew "node"
brew "nss"
brew "pigz"
brew "pinentry-mac"
brew "pv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "sloccount"
brew "socat"
brew "ssh-copy-id"
brew "starship"
brew "subversion"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "tsung", args: ["HEAD"]
brew "watch"
brew "watchman"
brew "whalebrew"
brew "yamllint"
brew "yarn"
brew "yj"
brew "youtube-dl"
brew "zoxide"
brew "zsh"
brew "buildkite/cli/bk"
brew "buildpacks/tap/pack"
brew "hashicorp/tap/boundary"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/vault"
brew "hashicorp/tap/waypoint"
brew "linuxkit/linuxkit/linuxkit", args: ["HEAD"]
brew "mutagen-io/mutagen/mutagen"
brew "outstand/desk/desk"
brew "tylerbrock/saw/saw"
brew "vitorgalvao/tiny-scripts/cask-repair"
brew "wagoodman/dive/dive"
cask "1password"
cask "airfoil"
cask "alfred"
cask "arduino"
cask "balenaetcher"
cask "bartender"
cask "brave-browser"
cask "chrysalis"
cask "cloudflare-warp"
cask "dash"
cask "discord"
cask "docker-edge"
cask "firefox"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "hammerspoon"
cask "handbrake"
cask "hashicorp-boundary-desktop"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "keepingyouawake"
cask "kitty"
cask "linear-linear"
cask "makemkv"
cask "multipass"
cask "ngrok"
cask "obsidian"
cask "paw"
cask "plex"
cask "proxyman"
cask "qbittorrent"
cask "session-manager-plugin"
cask "signal"
cask "slack"
cask "soundsource"
cask "spotify"
cask "steam"
cask "tableplus"
cask "transmission"
cask "viscosity"
cask "vlc"
cask "zoom"
mas "Bear", id: 1091189122
mas "Calcbot", id: 931657367
mas "CARROT Weather", id: 993487541
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "iFlicks 2", id: 731062389
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "MetaDoctor Pro", id: 992000603
mas "Mini Metro+", id: 1550663539
mas "Mini Motorways", id: 1456188526
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "Pixelmator", id: 407963104
mas "Playgrounds", id: 1496833156
mas "Spark", id: 1176895641
mas "Todoist", id: 585829637
mas "Tweetbot", id: 1384080005
mas "WireGuard", id: 1451685025
